#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Dec 28 19:59:24 CET 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim oscilloscope_tb_full_behav -key {Behavioral:sim_1:Functional:oscilloscope_tb_full} -tclbatch oscilloscope_tb_full.tcl -protoinst "protoinst_files/clock_gen.protoinst" -protoinst "protoinst_files/encoder.protoinst" -view /home/kris/Vivado/zamfp-project/video_generator_tb_behav.wcfg -log simulate.log"
xsim oscilloscope_tb_full_behav -key {Behavioral:sim_1:Functional:oscilloscope_tb_full} -tclbatch oscilloscope_tb_full.tcl -protoinst "protoinst_files/clock_gen.protoinst" -protoinst "protoinst_files/encoder.protoinst" -view /home/kris/Vivado/zamfp-project/video_generator_tb_behav.wcfg -log simulate.log

